CREATE TABLE account (
	id VARCHAR PRIMARY KEY,
	login VARCHAR UNIQUE NOT NULL,
	password VARCHAR NOT NULL,
	cpf VARCHAR NOT NULL,
	email VARCHAR NOT NULL,
	phone VARCHAR NOT NULL,
	cnpj VARCHAR NOT NULL,
	date TIMESTAMP NOT NULL
);
